import { parseLines, extractGenotype } from '../utils/parser'

describe('extractGenotype', () => {
  it('should extract genotype from standard format', () => {
    const columns = ['rs123', '1', '1000', 'AT']
    expect(extractGenotype(columns, '23andme')).toBe('AT')
  })

  it('should extract genotype from ancestry format', () => {
    const columns = ['rs123', '1', '1000', 'A', 'T']
    expect(extractGenotype(columns, 'ancestry')).toBe('A')
  })

  it('should return null for empty columns', () => {
    expect(extractGenotype([], '23andme')).toBeNull()
  })
})

describe('parseLines', () => {
  it('should parse 23andMe format lines', () => {
    const lines = [
      '# This data file generated by 23andMe',
      '# rsid\tchromosome\tposition\tgenotype',
      'rs123\t1\t1000\tAT',
      'rs456\t1\t2000\tGG',
      'rs789\t2\t3000\tCC',
    ]

    const result = parseLines(lines, '23andme')

    expect(result.size).toBe(3)
    expect(result.get('rs123')).toBe('AT')
    expect(result.get('rs456')).toBe('GG')
    expect(result.get('rs789')).toBe('CC')
  })

  it('should parse MyHeritage format lines', () => {
    const lines = ['# Uploaded from MyHeritage', 'rs111\t1\t100\tAA', 'rs222\t2\t200\tCG']

    const result = parseLines(lines, 'myheritage')

    expect(result.size).toBe(2)
    expect(result.get('rs111')).toBe('AA')
    expect(result.get('rs222')).toBe('CG')
  })

  it('should ignore comment lines', () => {
    const lines = ['# Comment 1', '# Comment 2', 'rs123\t1\t1000\tAT']

    const result = parseLines(lines, '23andme')

    expect(result.size).toBe(1)
  })

  it('should ignore empty lines', () => {
    const lines = ['', 'rs123\t1\t1000\tAT', '', 'rs456\t1\t2000\tGG']

    const result = parseLines(lines, '23andme')

    expect(result.size).toBe(2)
  })

  it('should ignore lines without rs prefix', () => {
    const lines = ['rs123\t1\t1000\tAT', 'i123\t1\t2000\tGG', 'chr1\t1\t3000\tCC']

    const result = parseLines(lines, '23andme')

    expect(result.size).toBe(1)
    expect(result.has('rs123')).toBe(true)
    expect(result.has('i123')).toBe(false)
  })

  it('should normalize genotypes to sorted order', () => {
    const lines = ['rs123\t1\t1000\tTA', 'rs456\t1\t2000\tGC']

    const result = parseLines(lines, '23andme')

    expect(result.get('rs123')).toBe('AT')
    expect(result.get('rs456')).toBe('CG')
  })

  it('should handle missing genotype as null', () => {
    const lines = ['rs123\t1\t1000\t--', 'rs456\t1\t2000\t00']

    const result = parseLines(lines, '23andme')

    expect(result.get('rs123')).toBeNull()
    expect(result.get('rs456')).toBeNull()
  })

  it('should handle CSV format with commas', () => {
    const lines = ['rs123,1,1000,AT', 'rs456,1,2000,GG']

    const result = parseLines(lines, '23andme')

    expect(result.size).toBe(2)
    expect(result.get('rs123')).toBe('AT')
  })
})
