import { detectVendor } from '../utils/vendor'

describe('detectVendor', () => {
  it('should detect MyHeritage files', () => {
    const lines = [
      '# Uploaded from MyHeritage DNA',
      '# rsid\tchromosome\tposition\tgenotype',
      'rs123\t1\t1000\tAA',
    ]
    expect(detectVendor(lines)).toBe('myheritage')
  })

  it('should detect 23andMe files', () => {
    const lines = [
      '# This data file generated by 23andMe at: Mon Jan 01 2024',
      '# 23andMe Inc.',
      'rs123\t1\t1000\tAA',
    ]
    expect(detectVendor(lines)).toBe('23andme')
  })

  it('should detect AncestryDNA files', () => {
    const lines = [
      '# AncestryDNA raw data download',
      '# This file was downloaded from AncestryDNA',
      'rs123\t1\t1000\tA\tA',
    ]
    expect(detectVendor(lines)).toBe('ancestry')
  })

  it('should return unknown for unrecognized formats', () => {
    const lines = ['# Some unknown DNA file', 'rs123\t1\t1000\tAA']
    expect(detectVendor(lines)).toBe('unknown')
  })

  it('should handle extra whitespace', () => {
    const lines = ['   # Uploaded from MyHeritage DNA   ', 'rs123\t1\t1000\tAA']
    expect(detectVendor(lines)).toBe('myheritage')
  })

  it('should handle case insensitivity', () => {
    const lines = ['# THIS DATA FILE GENERATED BY 23ANDME', 'rs123\t1\t1000\tAA']
    expect(detectVendor(lines)).toBe('23andme')
  })

  it('should handle empty lines', () => {
    const lines = ['', '', '# AncestryDNA raw data download', 'rs123\t1\t1000\tA\tA']
    expect(detectVendor(lines)).toBe('ancestry')
  })

  it('should return unknown for empty input', () => {
    expect(detectVendor([])).toBe('unknown')
  })
})
