export type VendorCode = 'myheritage' | '23andme' | 'ancestry' | 'unknown'

const MYHERITAGE_MARKERS = [
  '#uploaded from myheritage',
  '# myheritage',
  'generated by myheritage',
  '##fileformat=myheritage',
  '##format=mhv1.0',
  '##chip=gsa',
  '##reference=build37',
]

const TWENTY3_MARKERS = ['# this data file generated by 23andme', '23andme inc.', '# 23andme data']

const ANCESTRY_MARKERS = [
  '# ancestrydna raw data',
  '# this file was downloaded from ancestrydna',
  'ancestrydna, inc.',
]

const hasMarker = (line: string, markers: string[]) => {
  const normalized = line.trim().toLowerCase()
  return markers.some((marker) => normalized.startsWith(marker) || normalized.includes(marker))
}

export const detectVendor = (lines: string[]): VendorCode => {
  const sampleLines = lines.slice(0, 100)

  for (const line of sampleLines) {
    if (!line || line.startsWith('# rsid')) continue
    if (hasMarker(line, MYHERITAGE_MARKERS)) return 'myheritage'
    if (hasMarker(line, TWENTY3_MARKERS)) return '23andme'
    if (hasMarker(line, ANCESTRY_MARKERS)) return 'ancestry'
  }

  return 'unknown'
}
